version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-cluster
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-cluster
  kafka-rest-proxy:
      image: confluentinc/cp-kafka-rest:3.3.0
      ports:
        - "8081:8081"
        - "8082:8082"
      networks:
        - kafka-cluster
      environment:
        KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
        KAFKA_REST_LISTENERS: http://kafka-rest-proxy:8082
        KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-rest-proxy:8081
        KAFKA_REST_HOST_NAME: kafka-rest-proxy
networks:
  kafka-cluster:
